project_id = "bgdtekbhelormzbymkhh"

[functions.check-rate-limit]
verify_jwt = false

[functions.migrate-data]
verify_jwt = false

[functions.notify-missing-photo]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
