import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://cdn.jsdelivr.net/npm/resend@2.0.0/+esm";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface FailureAlertRequest {
  functionName: string;
  error: string;
  context?: Record<string, any>;
  timestamp?: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { functionName, error, context, timestamp }: FailureAlertRequest = await req.json();

    const emailResponse = await resend.emails.send({
      from: "Top10Lists Alerts <onboarding@resend.dev>",
      to: ["robert@top10lists.us"],
      subject: "APIFY GETDATA API FAILURE",
      html: `
        <h1>🚨 Apify API Failure Alert</h1>
        <p><strong>Function:</strong> ${functionName}</p>
        <p><strong>Time:</strong> ${timestamp || new Date().toISOString()}</p>
        <hr />
        <h2>Error Details:</h2>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 5px;">${error}</pre>
        ${context ? `
        <hr />
        <h2>Context:</h2>
        <pre style="background: #f5f5f5; padding: 15px; border-radius: 5px;">${JSON.stringify(context, null, 2)}</pre>
        ` : ''}
        <hr />
        <p style="color: #666; font-size: 12px;">
          This alert was automatically generated by the Top10Lists monitoring system.
        </p>
      `,
    });

    console.log("Failure alert email sent:", emailResponse);

    return new Response(JSON.stringify({ success: true, emailResponse }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error sending failure alert:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
};

serve(handler);
