-- Add social_twitter and social_tiktok columns to professionals table
ALTER TABLE public.professionals 
ADD COLUMN IF NOT EXISTS social_twitter text,
ADD COLUMN IF NOT EXISTS social_tiktok text;

-- Update the professionals_public view to include the new columns
DROP VIEW IF EXISTS public.professionals_public;

CREATE VIEW public.professionals_public AS
SELECT 
  id,
  business_address,
  certifications,
  certifications_verified,
  awards_verified,
  notable_achievements,
  press_mentions,
  publications,
  community_roles,
  languages,
  service_areas,
  license_issued_at,
  license_expires_at,
  review_stars_rating,
  num_total_reviews,
  ratings,
  platform_reviews,
  reviews_data,
  has_recent_review,
  most_recent_review_date,
  years_experience,
  total_sales,
  current_listings,
  agent_sales_stats,
  past_sales,
  rank,
  is_top_agent,
  is_premier_agent,
  is_brand_builder,
  city_id,
  category_id,
  active,
  team_display_information,
  professional_data,
  professional_information,
  agent_licenses,
  profile_types,
  profile_type_ids,
  created_at,
  updated_at,
  card_created_at,
  zillow_data_fetched_at,
  name,
  title,
  headline,
  type,
  email,
  phone,
  website,
  address,
  zip_code,
  image_url,
  og_image_url,
  sidebar_video_url,
  profile_link,
  review_link,
  zillow_profile_url,
  company,
  business_name,
  description,
  synthesized_bio,
  get_to_know_me,
  selection_rationale,
  specialty,
  badges,
  license_number,
  license_type,
  license_status,
  reviews_text,
  cpd_user_pronouns,
  social_facebook,
  social_instagram,
  social_linkedin,
  social_twitter,
  social_tiktok
FROM public.professionals;