// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

const memoryStorage: Storage = {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
  key: () => null,
  length: 0,
  clear: () => {},
};

function getAuthStorage(): Storage {
  try {
    if (typeof window !== 'undefined' && window.localStorage) return window.localStorage;
  } catch (_) {}
  return memoryStorage;
}

let supabaseInstance: SupabaseClient<Database>;

try {
  const storage = getAuthStorage();
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (typeof window !== 'undefined') {
      console.warn('[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. App will load; Supabase calls will fail until env is set in Vercel.');
    }
    supabaseInstance = createClient<Database>(
      SUPABASE_URL || 'https://placeholder.invalid',
      SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
      { auth: { storage, persistSession: true, autoRefreshToken: true } }
    );
  } else {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: { storage, persistSession: true, autoRefreshToken: true },
    });
  }
} catch (e) {
  console.error('[Supabase] Client init failed:', e);
  supabaseInstance = createClient<Database>('https://placeholder.invalid', 'placeholder-key', {
    auth: { storage: memoryStorage, persistSession: true, autoRefreshToken: true },
  });
}

export const supabase = supabaseInstance;